### PR TITLE
add MM-UPD

### PR DESCRIPTION
**Pull request by AtsuMiyai**
Thanks for your comprehensive codebase, which is very beneficial to the community!

Could you please add our [UPD](https://github.com/AtsuMiyai/UPD/tree/main) to your codebase?

I have tested the performances with LLaVA-1.5-13B and LLaVA-NeXT-34B and confirmed that the results are aligned with the paper's results.

Thank you.

### CODE REVIEW

**Review by kcz358 — COMMENTED** [review]
Hi, thank you for your contribution!

I have observed that the structure of most of the `_default_template` are similar expect for different `model_specific_prompt_kwargs`. Do you think it is possible to keep only one default_template and move model_specific_prompt_kwargs to the task yaml it corresponds to?

**Comment by AtsuMiyai** [comment]
@kcz358 Thanks for your feedback! Yes, we can merge them and remove the redundant `_default_template`.
I have updated the codes, so could you please check again?

**Review by kcz358 — APPROVED** [review]
Thank you for the changes. I have approved all these changes. Can you please provide a screenshot of your results that you get? Then I think we are good to merge.

**Comment by AtsuMiyai** [comment]
Super cool! 
I'll share screenshots of all the settings by testing LLaVA with the current code! (Maybe, I'll share them tomorrow.)

**Comment by AtsuMiyai** [comment]
@kcz358 I slightly changed` query_prompt ` in util.py to exactly match the official UPD code.

This is a screenshot with LLaVA1.5-13B. 

スクリーンショット 2024-06-02 23 29 34

Could you please merge our code?

**Comment by AtsuMiyai** [comment]
I'm really sorry for the many minor updates. I added the code for outputting json format because it is necessary to output the details of the result in json format for the leaderboard submission. 🙇

**Review by kcz358 — APPROVED** [review]
These changes seem good to me. Have you tested that the generated submission file can be successfully upload and submit to the leaderboard?

**Comment by Luodian** [comment]
Looks good, I think can merge now, thanks for contributing and reviewing！

**Pull request merged**
