### PR TITLE
Fix `LMMS_EVAL_PLUGINS`

### PR DESCRIPTION
**Pull request by zhijian-liu**

### CODE REVIEW

**Comment by zhijian-liu** [comment]
@Luodian, could you kindly review this PR if you are available? Thanks!

**Comment by Luodian** [comment]
> @Luodian, could you kindly review this PR if you are available? Thanks!

Hi, I am reviewing it, but could you kindly provide the information related my previous questions, thanks!

**Comment by zhijian-liu** [comment]
Hi @Luodian, thanks! I'm not able to find your question. Could you post it again?

**Review by kcz358 — APPROVED** [review]
From my reviewing, this is a PR that fix the previous `LMMS_EVAL_PLUGINS` that allow you to import your own model from another package. Currently all changes look good to me and the original model import is not affected.

Hi @zhijian-liu , may I ask is my understanding correct? If everything is good, I will merge this PR. Than you for your fix!

**Pull request merged**
