### PR TITLE
add task MMVet-v2

### PR DESCRIPTION
**Pull request by frankRenlf**
MM-Vet v2 is a extension of MMVet, which includes a new VL capability called "image-text sequence understanding", evaluating models' ability to process VL sequences.
paper: https://arxiv.org/abs/2408.00765
github: https://github.com/yuweihao/MM-Vet/tree/main/v2

Since the sample may have multiple images, it is provided mmvetv2_group_img.yaml for those models that cannot handle multiple image inputs.

### CODE REVIEW

**Comment by pufanyi** [comment]
Hi! Thank you so much for your contribution!!!!

It looks good to me! However, is it possible to add a simple comment before `mmvetv2_group_img.yaml`, something like (if I understood correctly):

```yaml
# This task differs from mmvet2 in that it combines multiple images into one, to accommodate models that cannot accept multiple images as input.
```

Thanks!!!

**Comment by frankRenlf** [comment]
> Hi! Thank you so much for your contribution!!!!
> 
> It looks good to me! However, is it possible to add a simple comment before `mmvetv2_group_img.yaml`, something like (if I understood correctly):
> 
> ```yaml
> # This task differs from mmvet2 in that it combines multiple images into one, to accommodate models that cannot accept multiple images as input.
> ```
> 
> Thanks!!!

Ok, I'll add this comment later

**Comment by pufanyi** [comment]
Thanks!!!

**Comment by Luodian** [comment]
image

Hi I think the evaluation still has some errors?

**Comment by frankRenlf** [comment]
> image
> Hi I think the evaluation still has some errors?

It seems that len of image_list is zero, the images should be stored in doc follow with image name as key. 
This works fine for me.
image

**Comment by pufanyi** [comment]
It seems that it is because there are 2 `doc_to_visual` functions in `utils.py`:

https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/d900496af837dcf5afe3d9efea471d624fd20588/lmms_eval/tasks/mmvetv2/utils.py#L165

https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/d900496af837dcf5afe3d9efea471d624fd20588/lmms_eval/tasks/mmvetv2/utils.py#L297

I have fixed it with some other errors in #457

**Pull request merged**
