### PR TITLE
[Feat] Add support for evaluation of InternVideo2-Chat && Fix evaluation for mvbench

### PR DESCRIPTION
**Pull request by yinanhe**
[Feat] Added support for InternVideo2-Chat model
[Feat] Add a new variable `revision` in `_default_template_yaml`. If you need to cache data from a branch that is not from `main` huggingface-dataset repo, you can add `revision` to the dataset field. The content can be branch or commit number to maintain the consistency of the evaluation
[Fix] The original implementation missed the'start 'and'end' of MVBench, fixed the reading from the video branch to avoid this problem

[Need Check] Modified the cache_dir field of mvbench _default_template_yaml, not sure if it will be automatically created

### CODE REVIEW

**Review by kcz358 — APPROVED** [review]
Hi, thank you for your contribution. You can auto fix the lint checking by using

```bash
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

After that should be good to merge.

Also a small question, may I ask will the `video` branch being merged into main on the huggingface later or the format of the dataset will change later? I saw that the video folder in the main branch contains video as zip files but the video branch contains lots of .mp4 files.

**Comment by yinanhe** [comment]
Thank you for your suggestion, we are implementing the relevant operation locally.

According to the current plan, the video branch will not be merged into the main branch. The zip in the main branch contains the original video of each data category for users to reproduce the original points. The video branch has been cropped and formatted through start and end. The score of MVBench will be slightly different.

**Comment by kcz358** [comment]
Thank you for your clarification. I believe the format would be okay as long as the video branch exists on the huggingface. The mp4 format would also be okay since we only search zip files to unzip. LGTM if the scores are mostly aligned!

**Review by kcz358 — APPROVED** [review]
Hi, I think this PR LGTM. Can you post a photo of the evaluation result (say some benchmarks other than then mvbench) using the new models for further reference? Then I will merge this PR. Thank you for your contribution!

**Review by Luodian — APPROVED** [review]

**Comment by kcz358** [comment]
Hi @yinanhe , I will merge this PR now. But if you have the evaluation results of the InternVIdeo2-Chat, please feel free to post it in the comment. Thank you!

**Comment by orrzohar** [comment]
One note; MVBench doesn't work for most LMMs, as some of the videos are stored as individual frames, and the logic of none of the LMMs I tested (llava onevison, vila, longva, internvl2, xcomposer, video-llava) is correct.

**Comment by kcz358** [comment]
Yep, I think that is true. Probably the format of the MVBench needs to revise further. Thanks @orrzohar .

@yinanhe May I ask can you fix the dataset format issue for the mvbench?

**Comment by kcz358** [comment]
Hi @orrzohar , may I ask a small question. It seems like the internvl video2 itself is using video path to read the MVBench but not video frames. So will the error still occur after using the `revision=video` in this PR? It seems the author have made all the data into .mp4 format.

**Comment by orrzohar** [comment]
Hi @kcz358,
Has MV-Bench been recently revised to entirely be comprised with mp4 files rather than pre-extracted video frames? I am using a version that is ~6 days old.
From my local version, some of MV-Bench was saved as mp4 files and some as several jpg files. Therefore, the 'visuals' is a list of PIL rather that a str indicating the path to the video. 
I found this as on MVBench, meny LMMs hit OOM as, rather than downsampling the number of frames, 100s of frames were input to the models leading.
Best,
Orr

**Comment by kcz358** [comment]
> Thank you for your suggestion, we are implementing the relevant operation locally.
> 
> According to the current plan, the video branch will not be merged into the main branch. The zip in the main branch contains the original video of each data category for users to reproduce the original points. The video branch has been cropped and formatted through start and end. The score of MVBench will be slightly different. But doing so can avoid users reading the test video incorrectly.
> 
> It is worth noting that since all the data in the video branch is already mp4, no additional decompression is required. I am not sure if I can directly read the video in '$HF_cache_dir/hub/datasets--OpenGVLab--MVBench' or create an additional hyperlinke. I hope the author can assist with this issue.

Hi @orrzohar , according to the description of the author of this PR, all the data are in mp4 format already. The fixed data version is in the branch `video` on huggingface. I do remember that in older versions, MVBench has some list of PIL.Image instead of mp4 path. But I think this error has been fixed now? So maybe if you repull the main branch again maybe the error can be fixed? Thank you!

**Pull request merged**
