### PR TITLE
[Minor] Update utils.py

### PR DESCRIPTION
**Pull request by YangYangGirl**
correct video path in videomme_dic_to_text+subtitle

### CODE REVIEW

**Comment by kcz358** [comment]
Hi @YangYangGirl , may I ask why would this additional hardcoded data path need to be added in the doc to visual function? I think current main branch should works well. If that is your default path in your own settings, maybe this change should be add into your own forked repo? If that is the case, I will close the PR.

**Comment by YangYangGirl** [comment]
The original video path in the main repo does not exist, resulting in total_frame = 0 and subtitle loading as none. It will run smoothly but result in inaccurate results.
image

**Comment by kcz358** [comment]
I think this problem has been fixed in commit [Fix videomme evaluation](https://github.com/EvolvingLMMs-Lab/lmms-eval/commit/3726b4f4714b5825bef9028828e985bd878a405d)? Current main branch seems already contains the path to data folder

https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/bfff5abcfbafa28ec5ae9a30418b9d5985606291/lmms_eval/tasks/videomme/utils.py#L176-L188

Seems like a duplicate fix. If this is the case, I will close this PR.

**Comment by YangYangGirl** [comment]
Thanks for the kind reply. But I checked again, in https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/bfff5abcfbafa28ec5ae9a30418b9d5985606291/lmms_eval/tasks/videomme/utils.py#L21, the video path is still wrong.

**Comment by kcz358** [comment]
Yeah @YangYangGirl , I see your point. You are correct. I think this is some version problem as we change the logic and default folder for unzipping files. I revise a little bit to make it not absolute path. I think current version should be correct?

**Comment by kcz358** [comment]
Have done a quick check here and subtitles should have loaded correctly.

image

merging this PR now and thank you for spotting the issue.

**Review by kcz358 — APPROVED** [review]

**Pull request merged**
