### PR TITLE
[Feat] Add support for evaluation of Oryx models

### PR DESCRIPTION
**Pull request by dongyh20**
Add Orxy models into lmms-eval/models to support image and video evaluations for Oryx

### CODE REVIEW

**Comment by Luodian** [comment]
Hi thanks for the contribution! But wondering if it can be merged into one file for both image & video operations, since there are plenty of duplicated code.

**Comment by dongyh20** [comment]
Working on it!

**Comment by dongyh20** [comment]
Add evaluation results using lmms-eval
results1

**Comment by kcz358** [comment]
LGTM after merging into the same model. May I ask do you have a screenshot of the evaluation result using current code and aligns with the paper?

**Comment by Luodian** [comment]
@dongyh20 Hi Yuhao, can you share one screenshot to show that the terminal results of oryx model matched in paper numbers?

**Comment by dongyh20** [comment]
Tested with Oryx-34B models

**Pull request merged**
