### PR TITLE
Support new task mmworld

### PR DESCRIPTION
**Pull request by jkooy**
> Before you open a pull-request, please check if a similar issue already exists or has been closed before.
> 
> ### When you open a pull-request, please be sure to include the following
> 
> - [x] A descriptive title: [xxx] XXXX
> - [x] A detailed description
> 
> Thank you for your contributions!
> 

Hi authors,

Thanks for your awesome work for creating such a useful tools!
This pull-request add a new task MMWorld https://mmworld-bench.github.io/, a new benchmark for multi-discipline, multi-faceted multimodal video understanding.

### CODE REVIEW

**Review by kcz358 — APPROVED** [review]
Thank you for the PR. LGTM

**Comment by jkooy** [comment]
Hi, here is the evaluation tested on my end. I have also fixed the lint issue
image

**Comment by jkooy** [comment]
> Thank you for the PR. Can you share a screenshot of a successful evaluation on this dataset and fix the lint issue? After that would be good to merge.
> 
> To auto fix the lint, you can use `pre-commit` and simply run `pre-commit run --all-files`


Hi, here is the evaluation tested on my end. I have also fixed the lint issue

image

**Comment by kcz358** [comment]
Thank you for your contribution @jkooy , LGTM!

**Pull request merged**
