### PR TITLE
[Model] support minimonkey model

### PR DESCRIPTION
**Pull request by white2018**
Before you open a pull-request, please check if a similar issue already exists or has been closed before.

### When you open a pull-request, please be sure to include the following

- [ ] A descriptive title: [xxx] XXXX
- [ ] A detailed description.

Thank you for your contributions!

This PR intends to enhance the functionality of lmms-eval by supporting MiniMonkey model in Monkey series, which is not covered in latest version.

### CODE REVIEW

**Review by kcz358 — APPROVED** [review]
Hi @white2018 , I think most of the changes look good. Can you share a screenshot of the evaluation result using this model? Then I think it will be good to merge.

**Comment by white2018** [comment]
> Hi @white2018 , I think most of the changes look good. Can you share a screenshot of the evaluation result using this model? Then I think it will be good to merge.

Hi @kcz358 , I run this evaluation code with mmstar dataset. Here is the screeshot as follows:
image

**Comment by kcz358** [comment]
@white2018 , the result looks good, can you do a final lint to pass the format checking? Current the workflow has failed. You can do it by
```bash
python3 -m pip install pre-commit
pre-commit install
pre-commit run --all-files
```
And simply commit the formatted files would be good. Thank you!

**Comment by white2018** [comment]
> @white2018 , the result looks good, can you do a final lint to pass the format checking? Current the workflow has failed. You can do it by
> 
> ```shell
> python3 -m pip install pre-commit
> pre-commit install
> pre-commit run --all-files
> ```
> 
> And simply commit the formatted files would be good. Thank you!

@kcz358 All right! I'll try it later. Thanks a lot

**Comment by kcz358** [comment]
Thank you for your contribution. Merging this PR now.

**Pull request merged**
